a = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('É numérico? {}'.format(a.isnumeric()))
print('Só tem espaços?', a.isspace())
print('É alfabético? {}'.format(a.isalpha()))
print('È alfanumérico? {}.'.format(a.isalnum()))
print('Está em maiúsculas? {}'.format(a.isupper()))
print('Está em minúsculas? {}'.format(a.islower()))
print('Está capitalizada? {}'.format(a.istitle()))